name: Generate ICS Schedule

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour UTC
  workflow_dispatch:       # Manual trigger

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 ics pytz selenium chromedriver-autoinstaller

      - name: Run calendar script
        run: python generate_ics.py

      - name: Commit updated ICS
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add schedule.ics
          git commit -m "Auto-update schedule.ics" || echo "No changes"
          git push
